=== maalvrei/clases/Lenguaje de marcas/05 Transformación XSL/06Ejemplo.dtd
<!ELEMENT ventas (producto+)>
<!ELEMENT producto (denominacion, pais, precio, año)>
<!ELEMENT denominacion (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT año (#PCDATA)>

=== maalvrei/clases/Lenguaje de marcas/05 Transformación XSL/06Ejemplo.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ventas SYSTEM "06Ejemplo.dtd">
<?xml-stylesheet type="text/xsl" href="06Ejemplo.xsl"?>
<ventas>
  <producto>
    <denominacion>Iglepiggle</denominacion>
    <pais>Alemania</pais>
    <precio>100.00</precio>
     <año>2009</año>
  </producto>
  <producto>
    <denominacion>Rustica Cale</denominacion>
    <pais>Francia</pais>
    <precio>19.99</precio>
    <año>2012</año>
  </producto>
</ventas>
