<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etiqueta[
<!ELEMENT etiqueta (nombre, calle*, ciudad, codigo, pais)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
]>
<etiqueta>
<nombre>Pepe García</nombre>
<calle>C/Ronda, 3</calle>
<ciudad>Sevilla</ciudad>
<codigo>18465</codigo> 
<pais>España</pais>
</etiqueta>