=== maalvrei/clases/Lenguaje de marcas/04 DTD Schema/Schema XML/prueba.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="documento">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="region1" type="xs:string"/>
        <xs:element ref="region2"/>
        <xs:element ref="region3"/>
        <xs:element ref="region4"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="region2">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ciudad" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="capital" type="xs:string" minOccurs="1"/>
        <xs:element name="ciudad" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="region3">
    <xs:complexType mixed="true">
      <xs:attribute name="habitantes" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="region4">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="nombre">
    <xs:complexType>
      <xs:attribute name="toponimia" type="xs:string" use="required"/>
      <xs:attribute name="habitantes" type="xs:integer" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== maalvrei/clases/Lenguaje de marcas/04 DTD Schema/Schema XML/prueba.xml
<?xml version="1.0" encoding="UTF-8"?>
<documento xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="prueba.xsd">
  <!-- CASO 1 -->
  <region1>Conchinchina</region1>
  
  <!-- CASO 2 -->
  <region2>
    <ciudad>Conchinchina</ciudad>
  </region2>
  
  <!-- CASO 3 -->
  <region3 habitantes="400.000">Conchinchina</region3>
  
  <!-- CASO 4 -->
  <region4><!-- habitantes debe ser menor 900000 y la toponimia es un texto con longitud entre 5 y 15  -->
    <nombre toponimia="Conchinchina" habitantes="400000"/>
    <nombre toponimia="Andalucía" habitantes="800000"/>
  </region4>
  
</documento>
