=== maalvrei/clases/Lenguaje de marcas/Ejercicios XML ESQUEMA/Ejercicio8XSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="biblioteca">

    <xs:complexType>
      <xs:sequence>
        <xs:element ref="libro" minOccurs="2" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="libro">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="autor" type="xs:string"  maxOccurs="3"/>
        <xs:element name="editorial" type="editorialType" minOccurs="1" maxOccurs="1"/>
        <xs:element name="edicion" type="xs:string" minOccurs="0"/>
        <xs:element name="isbn" type="isbnType"/>
        <xs:element name="donacion" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element name="ubicacion" type="tipoUbicacion"/>
        <xs:element name="fechaPublicacion" type="fechaType"/>
        <xs:element name="caracteristicas" type="caracteristicasType"/>
      </xs:sequence>
      <xs:attribute name="codigo" type="codigoType" use="required"/>
      <xs:attribute name="titulo" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="codigoType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-z]{3}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="isbnType">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{2}-\d{2}-\d{4}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fechaType">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{4}-\d{2}-\d{2}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="editorialType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Lengua de trapo"/>
      <xs:enumeration value="Libros del KO"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="tipoUbicacion">
    <xs:attribute name="sede" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="norte"/>
          <xs:enumeration value="sur"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

     <xs:complexType name="caracteristicasType">
      <xs:simpleType>
      <xs:restriction base="xs:string">
         <xs:enumeration value="rustica"/>
         <xs:enumeration value="bolsillo"/>
      </xs:restriction>
      </xs:simpleType>
   </xs:complexType>
  </xs:schema>

=== maalvrei/clases/Lenguaje de marcas/Ejercicios XML ESQUEMA/Ejercicio8XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio8XSD.xsd">
  <libro codigo="ABC" titulo="El Quijote">
    <autor>Cervantes Saavedra, Miguel de</autor>
    <autor>Pérez Galdós, Benito</autor>
    <editorial>Lengua de trapo</editorial>
    <isbn>12-34-5678</isbn>
    <ubicacion sede="norte"/>
    <fechaPublicacion>2005-10-01</fechaPublicacion>
    <caracteristicas>
      <numpaginas>500</numpaginas>
      <calidad>rustica</calidad>
    </caracteristicas>
  </libro>
  <libro codigo="XYZ" titulo="La Regenta">
    <autor>Alas, Leopoldo</autor>
    <editorial>Libros del KO</editorial>
    <isbn>98-76-5432</isbn>
    <ubicacion sede="sur"/>
    <fechaPublicacion>2010-05-15</fechaPublicacion>
    <caracteristicas>
      <numpaginas>300</numpaginas>
      <calidad>bolsillo</calidad>
    </caracteristicas>
  </libro>
</biblioteca>
