=== maalvrei/clases/Lenguaje de marcas/Ejercicios XML ESQUEMA/Repaso2DTD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="recetas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="receta" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" maxOccurs="unbounded">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="ingrediente" maxOccurs="unbounded">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="procedimiento" maxOccurs="unbounded">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="tiempo" maxOccurs="unbounded">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:minLength value="1"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== maalvrei/clases/Lenguaje de marcas/Ejercicios XML ESQUEMA/Repaso2DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<recetas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Repaso2DTD.xsd">
<receta>
<titulo>filetes</titulo>
<ingrediente>zanahoria</ingrediente>
<procedimiento>cocer</procedimiento>
<tiempo>2 horas</tiempo>
</receta>
<receta>
<titulo>pollo</titulo>
<ingrediente>zanahoria</ingrediente>
<procedimiento>cocer</procedimiento>
<tiempo>2 horas</tiempo>
</receta>
</recetas>
