=== maalvrei/clases/Lenguaje de marcas/04 DTD Schema/DTD/09Ediciones.dtd
<!ELEMENT ediciones (cabecera, tabla)>
<!ELEMENT cabecera (titulo, contenido, descripcion, fecha)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT contenido (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT tabla (region)>
<!ELEMENT region (norte, centro, sur)>
<!ELEMENT norte (nombre, (trimestre, lib_vendidos)+)>
<!ELEMENT centro (nombre, (trimestre, lib_vendidos)+)>
<!ELEMENT sur (nombre, (trimestre, lib_vendidos)+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT trimestre (#PCDATA)>
<!ELEMENT lib_vendidos (#PCDATA)>

=== maalvrei/clases/Lenguaje de marcas/04 DTD Schema/DTD/09Ediciones.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ediciones SYSTEM "09Ediciones.dtd">
<ediciones>
  <cabecera>
    <titulo>Ediciones</titulo>
    <contenido>Informe regional de ventas</contenido>
    <descripcion>Descripcion: informe de ventas para las regiones Norte, Centro y Sur</descripcion>
    <fecha>30/12/2009</fecha>
  </cabecera>
  <tabla>
      <norte>
        <nombre>Norte</nombre>
        <trimestre>1</trimestre>
        <lib_vendidos>24000</lib_vendidos>
        <trimestre>2</trimestre>
        <lib_vendidos>38600</lib_vendidos>
        <trimestre>3</trimestre>
        <lib_vendidos>NO_INFO</lib_vendidos>
        <trimestre>4</trimestre>
        <lib_vendidos>NO_INFO</lib_vendidos>
      </norte>
      <centro>
        <nombre>Centro</nombre>
        <trimestre>1</trimestre>
        <lib_vendidos>NO_INFO</lib_vendidos>
        <trimestre>2</trimestre>
        <lib_vendidos>16080</lib_vendidos>
        <trimestre>3</trimestre>
        <lib_vendidos>25000</lib_vendidos>
        <trimestre>4</trimestre>
        <lib_vendidos>29000</lib_vendidos>
      </centro>
      <sur>
        <nombre>Sur</nombre>
        <trimestre>1</trimestre>
        <lib_vendidos>27000</lib_vendidos>
        <trimestre>2</trimestre>
        <lib_vendidos>31400</lib_vendidos>
        <trimestre>3</trimestre>
        <lib_vendidos>40100</lib_vendidos>
        <trimestre>4</trimestre>
        <lib_vendidos>30000</lib_vendidos>
      </sur>
  </tabla>
</ediciones>
