=== maalvrei/clases/Lenguaje de marcas/06 Gestión y almacenamiento/miEjercicio2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pelicula">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" type="xs:string" />
              <xs:element name="director" type="xs:string" />
              <xs:element name="año" type="xs:integer" />
              <xs:element name="localizacion" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Continente">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="América del Sur" />
                          <xs:enumeration value="América del Norte" />
                          <xs:enumeration value="América Central" />
                          <xs:enumeration value="Europa" />
                          <xs:enumeration value="África" />
                          <xs:enumeration value="Asia" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="País" type="xs:string" />
                    <xs:element name="Capital">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="20" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="ID" type="xs:ID" use="required" />
                  <xs:attribute name="idResponsable" type="xs:IDREF" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="responsable" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="id" type="xs:ID" use="required" />
            <xs:attribute name="nombre" type="xs:string" use="required" />
            <xs:attribute name="apellidos" type="xs:string" use="required" />
            <xs:attribute name="telefono" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== maalvrei/clases/Lenguaje de marcas/06 Gestión y almacenamiento/miEjercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/Users/Tarde/Desktop/REPOSITORIOS/GITHUB%20MIGUE/clases/Lenguaje%20de%20marcas/06%20Gesti%C3%B3n%20y%20almacenamiento/miEjercicio2.xsd">
  <pelicula>
    <titulo>Viaje al corazón del hombre</titulo>
    <director>Romero Smith</director>
    <año>2019</año>
    <localizacion ID="loc1" idResponsable="resp1">
      <Continente>África</Continente>
      <País>Angola</País>
      <Capital>Luanda</Capital>
    </localizacion>
    <localizacion ID="loc2" idResponsable="resp2">
      <Continente>América del Norte</Continente>
      <País>Estados Unidos</País>
      <Capital>Washington DC</Capital>
    </localizacion>
    <localizacion ID="loc3" idResponsable="resp3">
      <Continente>América Central</Continente>
      <País>México</País>
      <Capital>Ciudad de México</Capital>
    </localizacion>
    <localizacion ID="loc4" idResponsable="resp4">
      <Continente>América del Sur</Continente>
      <País>Brasil</País>
      <Capital>Brasília</Capital>
    </localizacion>
    <localizacion ID="loc5" idResponsable="resp5">
      <Continente>Europa</Continente>
      <País>España</País>
      <Capital>Madrid</Capital>
    </localizacion>
  </pelicula>
  <responsable id="resp1" nombre="Juan" apellidos="Pérez" telefono="+244123456789" />
  <responsable id="resp2" nombre="John" apellidos="Doe" telefono="+12025551234" />
  <responsable id="resp3" nombre="José" apellidos="García" telefono="+525512345678" />
  <responsable id="resp4" nombre="João" apellidos="Silva" telefono="+5561987654321" />
  <responsable id="resp5" nombre="Carlos" apellidos="González" telefono="+34678901234" />
</root>
